AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Managed Blockchain. Creates peer node
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Peer Node configuration
        Parameters:
          - NetworkId
          - MemberId
          - PeerNodeInstanceType
          - PeerNodeAvailabilityZone


    ParameterLabels:
      NetworkId:
        default: Network ID
      MemberId:
        default: Member ID
      PeerNodeAvailabilityZone:
        default: Peer node Availability Zone
      PeerNodeInstanceType:
        default: Instance type
Parameters:
  NetworkId:
    Type: String
    Description: Network ID of your Amazon Managed Blockchain network.
  MemberId:
    Description: Member ID of your Amazon Managed Blockchain network.
    Type: String
  PeerNodeAvailabilityZone:
    Description: The Availability Zone for your first peer node.
    Default: us-east-1a
    Type: String
  PeerNodeInstanceType:
    Description: The type of compute instance to use for your peer nodes.
    Default: bc.t3.small
    Type: String
    AllowedValues:
      - bc.t3.small
      - bc.t3.medium
      - bc.t3.large
      - bc.t3.xlarge
      - bc.m5.large
      - bc.m5.xlarge
      - bc.m5.2xlarge
      - bc.m5.4xlarge
      - bc.c5.large
      - bc.c5.xlarge
      - bc.c5.2xlarge
      - bc.c5.4xlarge
    ConstraintDescription: >-
      If Edition is STARTER, then this value must be bc.t3.small
      or bc.t3.medium.
Resources:
  MemberPeerNode:
    Type: "AWS::ManagedBlockchain::Node"
    Properties:
      NetworkId: !Ref NetworkId
      MemberId: !Ref MemberId
      NodeConfiguration:
        InstanceType: !Ref PeerNodeInstanceType
        AvailabilityZone: !Ref PeerNodeAvailabilityZone
Outputs:
  MemberPeerNodeId:
    Description: member peer node Id
    Value: !GetAtt MemberPeerNode.NodeId



